In [1]:
import torch
import numpy

In [5]:
print("PyTorch CUDA version:", torch.version.cuda)
print("Whether CUDA available:", torch.cuda.is_available())
print("CUDA device name:", torch.cuda.get_device_name(0))
print("CUDA device count:", torch.cuda.device_count())

PyTorch CUDA version: 11.6
Whether CUDA available: True
CUDA device name: NVIDIA GeForce GTX 1660 SUPER
CUDA device count: 1


## Example on Swarma Book

In [17]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.grad_fn

In [18]:
z = y * y
z.grad_fn

In [20]:
t = torch.mean(z)
t.backward()

In [21]:
print(z.grad)
print(y.grad)
print(x.grad)

None
None
tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


C:\Users\Cover\AppData\Local\Temp\ipykernel_13412\1195348714.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:485.)
  print(z.grad)
C:\Users\Cover\AppData\Local\Temp\ipykernel_13412\1195348714.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor

## Example on D2L

In [27]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [28]:
x.requires_grad_(True)
print(x.grad)

None


In [29]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [30]:
# backpropagation can only be called once
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [31]:
x.grad == 4 * x

tensor([True, True, True, True])

In [32]:
x.grad.zero_()
y = x.sum()
y.backward()
# linear sum of x, so the gradient is 1
x.grad

tensor([1., 1., 1., 1.])

### Detached computation

In [33]:

x.grad.zero_() # set gradient to zero
y = x * x
u = y.detach() # detach y from the computation graph
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [35]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [36]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [38]:
a.grad == d / a

tensor(True)

### Device

In [2]:
X = torch.ones(2, 3, device='cpu')
Y = torch.ones(2, 3, device='cuda')

In [4]:
try:
    Z = X + Y
except RuntimeError as e:
    print("Should on the same device")

Should on the same device


In [5]:
X = X.to('cuda')
Z = X + Y